### ISSUE TITLE
Bug: Advanced Settings not showing when Custom Level Cost Text Installed

### ISSUE THREAD

**Issue by andrewlimaza** [strangerstudios/pmpro-failed-payment-limit#6]
The advanced settings for Failed Payment Limit doesn't show when the Custom Level Cost Text Add On is activated.

**Comment by fcastroa** [comment]
confirmed issue still exists almost a year later, pretty ridiculous

**Comment by dparker1005** [comment]
This bug has been fixed in the Custom Level Cost Text Add On.
